repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-case-conflict
      - id: check-byte-order-marker
      - id: check-added-large-files
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: [--no-sort-keys]
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-build
      - id: golangci-lint
